### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by maxence-lefort**

### CODE REVIEW

**Comment by maxence-lefort** [comment]
@haffo @HossamT @ncrouzier-nist Can you review please?

**Review by afrold — APPROVED** [review]

**Comment by afrold** [comment]
done

**Comment by afrold** [comment]
can you do the wiki the process to upstream to the latest of the code on hit-base ?

**Comment by maxence-lefort** [comment]
It works the same as a fork, see more info here:
https://help.github.com/articles/configuring-a-remote-for-a-fork/

**Comment by afrold** [comment]
ok, cool. thanks.

**Pull request merged**
